# Generated by Django 3.2.2 on 2021-05-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('desctription', models.TextField(blank=True)),
                ('cat_image', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
    ]
