# Generated by Django 3.2.2 on 2021-06-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='trending_product',
            field=models.BooleanField(default=False),
        ),
    ]
